# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gestionNotesNSI.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1026, 986)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabApplication = QtWidgets.QTabWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabApplication.sizePolicy().hasHeightForWidth())
        self.tabApplication.setSizePolicy(sizePolicy)
        self.tabApplication.setObjectName("tabApplication")
        self.tabAdministration = QtWidgets.QWidget()
        self.tabAdministration.setObjectName("tabAdministration")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tabAdministration)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.tabAdministration)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.cbFiltreAnnee = QtWidgets.QComboBox(self.groupBox)
        self.cbFiltreAnnee.setObjectName("cbFiltreAnnee")
        self.horizontalLayout_2.addWidget(self.cbFiltreAnnee)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 1)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.cbFiltreNiveau = QtWidgets.QComboBox(self.groupBox)
        self.cbFiltreNiveau.setObjectName("cbFiltreNiveau")
        self.horizontalLayout_4.addWidget(self.cbFiltreNiveau)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 1)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_7.setStretch(0, 1)
        self.horizontalLayout_7.setStretch(1, 1)
        self.gridLayout.addLayout(self.horizontalLayout_7, 0, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 1)
        self.horizontalLayout_3.setStretch(2, 1)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 1, 1, 1)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.leClasse = QtWidgets.QLineEdit(self.groupBox)
        self.leClasse.setInputMask("")
        self.leClasse.setText("")
        self.leClasse.setObjectName("leClasse")
        self.horizontalLayout_17.addWidget(self.leClasse)
        self.cbNiveau = QtWidgets.QComboBox(self.groupBox)
        self.cbNiveau.setObjectName("cbNiveau")
        self.horizontalLayout_17.addWidget(self.cbNiveau)
        self.cbProfPrincipal = QtWidgets.QComboBox(self.groupBox)
        self.cbProfPrincipal.setObjectName("cbProfPrincipal")
        self.horizontalLayout_17.addWidget(self.cbProfPrincipal)
        self.horizontalLayout_17.setStretch(0, 1)
        self.horizontalLayout_17.setStretch(1, 1)
        self.horizontalLayout_17.setStretch(2, 1)
        self.gridLayout.addLayout(self.horizontalLayout_17, 2, 1, 1, 1)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.pbAjouterClasse = QtWidgets.QPushButton(self.groupBox)
        self.pbAjouterClasse.setObjectName("pbAjouterClasse")
        self.horizontalLayout_18.addWidget(self.pbAjouterClasse)
        self.pbSupprimerClasse = QtWidgets.QPushButton(self.groupBox)
        self.pbSupprimerClasse.setObjectName("pbSupprimerClasse")
        self.horizontalLayout_18.addWidget(self.pbSupprimerClasse)
        self.pbModifierClasse = QtWidgets.QPushButton(self.groupBox)
        self.pbModifierClasse.setObjectName("pbModifierClasse")
        self.horizontalLayout_18.addWidget(self.pbModifierClasse)
        self.horizontalLayout_18.setStretch(0, 1)
        self.horizontalLayout_18.setStretch(1, 1)
        self.horizontalLayout_18.setStretch(2, 1)
        self.gridLayout.addLayout(self.horizontalLayout_18, 3, 1, 1, 1)
        self.twClasses = QtWidgets.QTableWidget(self.groupBox)
        self.twClasses.setColumnCount(4)
        self.twClasses.setObjectName("twClasses")
        self.twClasses.setRowCount(0)
        self.twClasses.horizontalHeader().setCascadingSectionResizes(True)
        self.twClasses.horizontalHeader().setDefaultSectionSize(100)
        self.twClasses.horizontalHeader().setMinimumSectionSize(100)
        self.twClasses.horizontalHeader().setSortIndicatorShown(False)
        self.twClasses.horizontalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.twClasses, 0, 0, 4, 1)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tabAdministration)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.leLibelleMatiere = QtWidgets.QLineEdit(self.groupBox_2)
        self.leLibelleMatiere.setObjectName("leLibelleMatiere")
        self.horizontalLayout_6.addWidget(self.leLibelleMatiere)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 2)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 0, 1, 1, 1)
        self.twMatieres = QtWidgets.QTableWidget(self.groupBox_2)
        self.twMatieres.setColumnCount(2)
        self.twMatieres.setObjectName("twMatieres")
        self.twMatieres.setRowCount(0)
        self.twMatieres.horizontalHeader().setCascadingSectionResizes(True)
        self.twMatieres.horizontalHeader().setDefaultSectionSize(150)
        self.twMatieres.horizontalHeader().setMinimumSectionSize(100)
        self.twMatieres.horizontalHeader().setSortIndicatorShown(False)
        self.twMatieres.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_2.addWidget(self.twMatieres, 0, 0, 3, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.leDescriptionMatiere = QtWidgets.QLineEdit(self.groupBox_2)
        self.leDescriptionMatiere.setObjectName("leDescriptionMatiere")
        self.horizontalLayout.addWidget(self.leDescriptionMatiere)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 1, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pbAjouterMatiere = QtWidgets.QPushButton(self.groupBox_2)
        self.pbAjouterMatiere.setObjectName("pbAjouterMatiere")
        self.verticalLayout_6.addWidget(self.pbAjouterMatiere)
        self.horizontalLayout_5.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pbSupprimerMatiere = QtWidgets.QPushButton(self.groupBox_2)
        self.pbSupprimerMatiere.setObjectName("pbSupprimerMatiere")
        self.verticalLayout_7.addWidget(self.pbSupprimerMatiere)
        self.horizontalLayout_5.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.pbModifierMatiere = QtWidgets.QPushButton(self.groupBox_2)
        self.pbModifierMatiere.setObjectName("pbModifierMatiere")
        self.verticalLayout_8.addWidget(self.pbModifierMatiere)
        self.horizontalLayout_5.addLayout(self.verticalLayout_8)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 1)
        self.horizontalLayout_5.setStretch(2, 1)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 2, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tabAdministration)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.twProfesseurs = QtWidgets.QTableWidget(self.groupBox_3)
        self.twProfesseurs.setColumnCount(3)
        self.twProfesseurs.setObjectName("twProfesseurs")
        self.twProfesseurs.setRowCount(0)
        self.twProfesseurs.horizontalHeader().setCascadingSectionResizes(True)
        self.twProfesseurs.horizontalHeader().setDefaultSectionSize(150)
        self.twProfesseurs.horizontalHeader().setMinimumSectionSize(120)
        self.twProfesseurs.horizontalHeader().setSortIndicatorShown(False)
        self.twProfesseurs.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_3.addWidget(self.twProfesseurs, 0, 0, 2, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_8.addWidget(self.label_9)
        self.leIdProfesseur = QtWidgets.QLineEdit(self.groupBox_3)
        self.leIdProfesseur.setObjectName("leIdProfesseur")
        self.horizontalLayout_8.addWidget(self.leIdProfesseur)
        self.horizontalLayout_8.setStretch(0, 1)
        self.horizontalLayout_8.setStretch(1, 2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_11.addWidget(self.label_11)
        self.leNomProfesseur = QtWidgets.QLineEdit(self.groupBox_3)
        self.leNomProfesseur.setObjectName("leNomProfesseur")
        self.horizontalLayout_11.addWidget(self.leNomProfesseur)
        self.horizontalLayout_11.setStretch(0, 1)
        self.horizontalLayout_11.setStretch(1, 2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_9.addWidget(self.label_10)
        self.lePrenomProfesseur = QtWidgets.QLineEdit(self.groupBox_3)
        self.lePrenomProfesseur.setObjectName("lePrenomProfesseur")
        self.horizontalLayout_9.addWidget(self.lePrenomProfesseur)
        self.horizontalLayout_9.setStretch(0, 1)
        self.horizontalLayout_9.setStretch(1, 2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.gridLayout_3.addLayout(self.verticalLayout_3, 0, 1, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.pbAjouterProfesseur = QtWidgets.QPushButton(self.groupBox_3)
        self.pbAjouterProfesseur.setObjectName("pbAjouterProfesseur")
        self.verticalLayout_11.addWidget(self.pbAjouterProfesseur)
        self.horizontalLayout_10.addLayout(self.verticalLayout_11)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.pbSupprimerProfesseur = QtWidgets.QPushButton(self.groupBox_3)
        self.pbSupprimerProfesseur.setObjectName("pbSupprimerProfesseur")
        self.verticalLayout_12.addWidget(self.pbSupprimerProfesseur)
        self.horizontalLayout_10.addLayout(self.verticalLayout_12)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.pbModifierProfesseur = QtWidgets.QPushButton(self.groupBox_3)
        self.pbModifierProfesseur.setObjectName("pbModifierProfesseur")
        self.verticalLayout_13.addWidget(self.pbModifierProfesseur)
        self.horizontalLayout_10.addLayout(self.verticalLayout_13)
        self.horizontalLayout_10.setStretch(0, 1)
        self.horizontalLayout_10.setStretch(1, 1)
        self.horizontalLayout_10.setStretch(2, 1)
        self.gridLayout_3.addLayout(self.horizontalLayout_10, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tabAdministration)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.twAdministrationEleves = QtWidgets.QTableWidget(self.groupBox_4)
        self.twAdministrationEleves.setColumnCount(4)
        self.twAdministrationEleves.setObjectName("twAdministrationEleves")
        self.twAdministrationEleves.setRowCount(0)
        self.twAdministrationEleves.horizontalHeader().setCascadingSectionResizes(True)
        self.twAdministrationEleves.horizontalHeader().setDefaultSectionSize(115)
        self.twAdministrationEleves.horizontalHeader().setMinimumSectionSize(50)
        self.twAdministrationEleves.horizontalHeader().setSortIndicatorShown(False)
        self.twAdministrationEleves.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_4.addWidget(self.twAdministrationEleves, 0, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_12 = QtWidgets.QLabel(self.groupBox_4)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_12.addWidget(self.label_12)
        self.leIdEleve = QtWidgets.QLineEdit(self.groupBox_4)
        self.leIdEleve.setObjectName("leIdEleve")
        self.horizontalLayout_12.addWidget(self.leIdEleve)
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_12.addWidget(self.label_6)
        self.cbAdministrationClasse = QtWidgets.QComboBox(self.groupBox_4)
        self.cbAdministrationClasse.setObjectName("cbAdministrationClasse")
        self.horizontalLayout_12.addWidget(self.cbAdministrationClasse)
        self.horizontalLayout_12.setStretch(0, 1)
        self.horizontalLayout_12.setStretch(1, 2)
        self.horizontalLayout_12.setStretch(2, 1)
        self.horizontalLayout_12.setStretch(3, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_13 = QtWidgets.QLabel(self.groupBox_4)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_13.addWidget(self.label_13)
        self.leNomEleve = QtWidgets.QLineEdit(self.groupBox_4)
        self.leNomEleve.setObjectName("leNomEleve")
        self.horizontalLayout_13.addWidget(self.leNomEleve)
        self.horizontalLayout_13.setStretch(0, 1)
        self.horizontalLayout_13.setStretch(1, 2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_14 = QtWidgets.QLabel(self.groupBox_4)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_14.addWidget(self.label_14)
        self.lePrenomEleve = QtWidgets.QLineEdit(self.groupBox_4)
        self.lePrenomEleve.setObjectName("lePrenomEleve")
        self.horizontalLayout_14.addWidget(self.lePrenomEleve)
        self.horizontalLayout_14.setStretch(0, 1)
        self.horizontalLayout_14.setStretch(1, 2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.pbAjouterEleve = QtWidgets.QPushButton(self.groupBox_4)
        self.pbAjouterEleve.setObjectName("pbAjouterEleve")
        self.verticalLayout_14.addWidget(self.pbAjouterEleve)
        self.horizontalLayout_15.addLayout(self.verticalLayout_14)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.pbSupprimerEleve = QtWidgets.QPushButton(self.groupBox_4)
        self.pbSupprimerEleve.setObjectName("pbSupprimerEleve")
        self.verticalLayout_15.addWidget(self.pbSupprimerEleve)
        self.horizontalLayout_15.addLayout(self.verticalLayout_15)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.pbModifierEleve = QtWidgets.QPushButton(self.groupBox_4)
        self.pbModifierEleve.setObjectName("pbModifierEleve")
        self.verticalLayout_16.addWidget(self.pbModifierEleve)
        self.horizontalLayout_15.addLayout(self.verticalLayout_16)
        self.horizontalLayout_15.setStretch(0, 1)
        self.horizontalLayout_15.setStretch(1, 1)
        self.horizontalLayout_15.setStretch(2, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_15)
        self.gridLayout_4.addLayout(self.verticalLayout_4, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        self.tabApplication.addTab(self.tabAdministration, "")
        self.tabProfesseur = QtWidgets.QWidget()
        self.tabProfesseur.setObjectName("tabProfesseur")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.tabProfesseur)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.gbIdentificationProfesseur = QtWidgets.QGroupBox(self.tabProfesseur)
        self.gbIdentificationProfesseur.setObjectName("gbIdentificationProfesseur")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.gbIdentificationProfesseur)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_16.setContentsMargins(-1, 1, -1, 1)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_15 = QtWidgets.QLabel(self.gbIdentificationProfesseur)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_16.addWidget(self.label_15)
        self.cbIdentificationProfesseur = QtWidgets.QComboBox(self.gbIdentificationProfesseur)
        self.cbIdentificationProfesseur.setMinimumSize(QtCore.QSize(200, 0))
        self.cbIdentificationProfesseur.setObjectName("cbIdentificationProfesseur")
        self.horizontalLayout_16.addWidget(self.cbIdentificationProfesseur)
        self.label_20 = QtWidgets.QLabel(self.gbIdentificationProfesseur)
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_16.addWidget(self.label_20)
        self.cbSelectionClasseProfesseur = QtWidgets.QComboBox(self.gbIdentificationProfesseur)
        self.cbSelectionClasseProfesseur.setEnabled(False)
        self.cbSelectionClasseProfesseur.setObjectName("cbSelectionClasseProfesseur")
        self.horizontalLayout_16.addWidget(self.cbSelectionClasseProfesseur)
        self.label_16 = QtWidgets.QLabel(self.gbIdentificationProfesseur)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_16.addWidget(self.label_16)
        self.cbSelectionMatiereProfesseur = QtWidgets.QComboBox(self.gbIdentificationProfesseur)
        self.cbSelectionMatiereProfesseur.setEnabled(False)
        self.cbSelectionMatiereProfesseur.setMinimumSize(QtCore.QSize(200, 0))
        self.cbSelectionMatiereProfesseur.setObjectName("cbSelectionMatiereProfesseur")
        self.horizontalLayout_16.addWidget(self.cbSelectionMatiereProfesseur)
        self.verticalLayout_5.addLayout(self.horizontalLayout_16)
        self.verticalLayout_17.addWidget(self.gbIdentificationProfesseur)
        self.gbIdentificationProfesseur_3 = QtWidgets.QGroupBox(self.tabProfesseur)
        self.gbIdentificationProfesseur_3.setObjectName("gbIdentificationProfesseur_3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.gbIdentificationProfesseur_3)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_21.setContentsMargins(-1, 1, -1, 1)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_24 = QtWidgets.QLabel(self.gbIdentificationProfesseur_3)
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_21.addWidget(self.label_24)
        self.leNouveauDevoir = QtWidgets.QLineEdit(self.gbIdentificationProfesseur_3)
        self.leNouveauDevoir.setEnabled(False)
        self.leNouveauDevoir.setObjectName("leNouveauDevoir")
        self.horizontalLayout_21.addWidget(self.leNouveauDevoir)
        self.pbAjouterDevoir = QtWidgets.QPushButton(self.gbIdentificationProfesseur_3)
        self.pbAjouterDevoir.setObjectName("pbAjouterDevoir")
        self.horizontalLayout_21.addWidget(self.pbAjouterDevoir)
        self.horizontalLayout_21.setStretch(0, 1)
        self.horizontalLayout_21.setStretch(1, 2)
        self.horizontalLayout_21.setStretch(2, 2)
        self.verticalLayout_10.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_26 = QtWidgets.QLabel(self.gbIdentificationProfesseur_3)
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_22.addWidget(self.label_26)
        self.cbSelectionDevoirSupprimer = QtWidgets.QComboBox(self.gbIdentificationProfesseur_3)
        self.cbSelectionDevoirSupprimer.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbSelectionDevoirSupprimer.sizePolicy().hasHeightForWidth())
        self.cbSelectionDevoirSupprimer.setSizePolicy(sizePolicy)
        self.cbSelectionDevoirSupprimer.setObjectName("cbSelectionDevoirSupprimer")
        self.horizontalLayout_22.addWidget(self.cbSelectionDevoirSupprimer)
        self.pbSupprimerDevoir = QtWidgets.QPushButton(self.gbIdentificationProfesseur_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbSupprimerDevoir.sizePolicy().hasHeightForWidth())
        self.pbSupprimerDevoir.setSizePolicy(sizePolicy)
        self.pbSupprimerDevoir.setObjectName("pbSupprimerDevoir")
        self.horizontalLayout_22.addWidget(self.pbSupprimerDevoir)
        self.horizontalLayout_22.setStretch(0, 1)
        self.horizontalLayout_22.setStretch(1, 2)
        self.horizontalLayout_22.setStretch(2, 2)
        self.verticalLayout_10.addLayout(self.horizontalLayout_22)
        self.verticalLayout_17.addWidget(self.gbIdentificationProfesseur_3)
        self.gbIdentificationProfesseur_2 = QtWidgets.QGroupBox(self.tabProfesseur)
        self.gbIdentificationProfesseur_2.setObjectName("gbIdentificationProfesseur_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.gbIdentificationProfesseur_2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setContentsMargins(-1, 1, -1, 1)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_18 = QtWidgets.QLabel(self.gbIdentificationProfesseur_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_20.addWidget(self.label_18)
        self.cbDevoirSelectionDevoirEnregistrerNotes = QtWidgets.QComboBox(self.gbIdentificationProfesseur_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbDevoirSelectionDevoirEnregistrerNotes.sizePolicy().hasHeightForWidth())
        self.cbDevoirSelectionDevoirEnregistrerNotes.setSizePolicy(sizePolicy)
        self.cbDevoirSelectionDevoirEnregistrerNotes.setObjectName("cbDevoirSelectionDevoirEnregistrerNotes")
        self.horizontalLayout_20.addWidget(self.cbDevoirSelectionDevoirEnregistrerNotes)
        self.pbEnregistrerNotes = QtWidgets.QPushButton(self.gbIdentificationProfesseur_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbEnregistrerNotes.sizePolicy().hasHeightForWidth())
        self.pbEnregistrerNotes.setSizePolicy(sizePolicy)
        self.pbEnregistrerNotes.setBaseSize(QtCore.QSize(0, 0))
        self.pbEnregistrerNotes.setObjectName("pbEnregistrerNotes")
        self.horizontalLayout_20.addWidget(self.pbEnregistrerNotes)
        self.horizontalLayout_20.setStretch(0, 1)
        self.horizontalLayout_20.setStretch(1, 2)
        self.horizontalLayout_20.setStretch(2, 2)
        self.verticalLayout_9.addLayout(self.horizontalLayout_20)
        self.twProfesseurAfficherNotes = QtWidgets.QTableWidget(self.gbIdentificationProfesseur_2)
        self.twProfesseurAfficherNotes.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.twProfesseurAfficherNotes.setColumnCount(6)
        self.twProfesseurAfficherNotes.setObjectName("twProfesseurAfficherNotes")
        self.twProfesseurAfficherNotes.setRowCount(0)
        self.twProfesseurAfficherNotes.horizontalHeader().setCascadingSectionResizes(True)
        self.twProfesseurAfficherNotes.horizontalHeader().setDefaultSectionSize(160)
        self.twProfesseurAfficherNotes.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_9.addWidget(self.twProfesseurAfficherNotes)
        self.verticalLayout_17.addWidget(self.gbIdentificationProfesseur_2)
        self.tabApplication.addTab(self.tabProfesseur, "")
        self.tabAssociation = QtWidgets.QWidget()
        self.tabAssociation.setObjectName("tabAssociation")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.tabAssociation)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.gbIdentificationProfesseur_4 = QtWidgets.QGroupBox(self.tabAssociation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbIdentificationProfesseur_4.sizePolicy().hasHeightForWidth())
        self.gbIdentificationProfesseur_4.setSizePolicy(sizePolicy)
        self.gbIdentificationProfesseur_4.setMaximumSize(QtCore.QSize(16777215, 100))
        self.gbIdentificationProfesseur_4.setObjectName("gbIdentificationProfesseur_4")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.gbIdentificationProfesseur_4)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_19.setContentsMargins(-1, 1, -1, 1)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_17 = QtWidgets.QLabel(self.gbIdentificationProfesseur_4)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_19.addWidget(self.label_17)
        self.cbAssociationProfesseur = QtWidgets.QComboBox(self.gbIdentificationProfesseur_4)
        self.cbAssociationProfesseur.setMinimumSize(QtCore.QSize(200, 0))
        self.cbAssociationProfesseur.setObjectName("cbAssociationProfesseur")
        self.horizontalLayout_19.addWidget(self.cbAssociationProfesseur)
        self.label_19 = QtWidgets.QLabel(self.gbIdentificationProfesseur_4)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_19.addWidget(self.label_19)
        self.lblNUMEN = QtWidgets.QLabel(self.gbIdentificationProfesseur_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblNUMEN.setFont(font)
        self.lblNUMEN.setText("")
        self.lblNUMEN.setObjectName("lblNUMEN")
        self.horizontalLayout_19.addWidget(self.lblNUMEN)
        self.horizontalLayout_19.setStretch(0, 1)
        self.horizontalLayout_19.setStretch(1, 2)
        self.horizontalLayout_19.setStretch(2, 1)
        self.horizontalLayout_19.setStretch(3, 4)
        self.verticalLayout_18.addLayout(self.horizontalLayout_19)
        self.verticalLayout_19.addWidget(self.gbIdentificationProfesseur_4)
        self.gbEnseigne = QtWidgets.QGroupBox(self.tabAssociation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbEnseigne.sizePolicy().hasHeightForWidth())
        self.gbEnseigne.setSizePolicy(sizePolicy)
        self.gbEnseigne.setObjectName("gbEnseigne")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.gbEnseigne)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.verticalLayout_19.addWidget(self.gbEnseigne)
        self.tabApplication.addTab(self.tabAssociation, "")
        self.tabEleve = QtWidgets.QWidget()
        self.tabEleve.setObjectName("tabEleve")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.tabEleve)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.gbIdentificationEleve = QtWidgets.QGroupBox(self.tabEleve)
        self.gbIdentificationEleve.setObjectName("gbIdentificationEleve")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.gbIdentificationEleve)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_23.setContentsMargins(-1, 1, -1, 1)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_22 = QtWidgets.QLabel(self.gbIdentificationEleve)
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_23.addWidget(self.label_22)
        self.cbSelectionClasseEleve = QtWidgets.QComboBox(self.gbIdentificationEleve)
        self.cbSelectionClasseEleve.setEnabled(True)
        self.cbSelectionClasseEleve.setObjectName("cbSelectionClasseEleve")
        self.horizontalLayout_23.addWidget(self.cbSelectionClasseEleve)
        self.label_21 = QtWidgets.QLabel(self.gbIdentificationEleve)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_23.addWidget(self.label_21)
        self.cbIdentificationEleve = QtWidgets.QComboBox(self.gbIdentificationEleve)
        self.cbIdentificationEleve.setEnabled(False)
        self.cbIdentificationEleve.setMinimumSize(QtCore.QSize(200, 0))
        self.cbIdentificationEleve.setObjectName("cbIdentificationEleve")
        self.horizontalLayout_23.addWidget(self.cbIdentificationEleve)
        self.label_23 = QtWidgets.QLabel(self.gbIdentificationEleve)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_23.addWidget(self.label_23)
        self.cbSelectionMatiereEleve = QtWidgets.QComboBox(self.gbIdentificationEleve)
        self.cbSelectionMatiereEleve.setEnabled(False)
        self.cbSelectionMatiereEleve.setMinimumSize(QtCore.QSize(200, 0))
        self.cbSelectionMatiereEleve.setObjectName("cbSelectionMatiereEleve")
        self.horizontalLayout_23.addWidget(self.cbSelectionMatiereEleve)
        self.verticalLayout_20.addLayout(self.horizontalLayout_23)
        self.verticalLayout_23.addWidget(self.gbIdentificationEleve)
        self.gbNotesEleve = QtWidgets.QGroupBox(self.tabEleve)
        self.gbNotesEleve.setObjectName("gbNotesEleve")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.gbNotesEleve)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.twEleveAfficherNotes = QtWidgets.QTableWidget(self.gbNotesEleve)
        self.twEleveAfficherNotes.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.twEleveAfficherNotes.setColumnCount(5)
        self.twEleveAfficherNotes.setObjectName("twEleveAfficherNotes")
        self.twEleveAfficherNotes.setRowCount(0)
        self.twEleveAfficherNotes.horizontalHeader().setCascadingSectionResizes(True)
        self.twEleveAfficherNotes.horizontalHeader().setDefaultSectionSize(190)
        self.twEleveAfficherNotes.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_22.addWidget(self.twEleveAfficherNotes)
        self.verticalLayout_23.addWidget(self.gbNotesEleve)
        self.tabApplication.addTab(self.tabEleve, "")
        self.verticalLayout.addWidget(self.tabApplication)

        self.retranslateUi(Dialog)
        self.tabApplication.setCurrentIndex(3)
        self.cbFiltreAnnee.currentTextChanged['QString'].connect(Dialog.on_change_annee)
        self.pbSupprimerClasse.clicked.connect(Dialog.pbSupprimerClasse_clicked)
        self.cbFiltreNiveau.currentTextChanged['QString'].connect(Dialog.on_change_niveau)
        self.twClasses.itemClicked['QTableWidgetItem*'].connect(Dialog.on_administration_selection_classe)
        self.pbAjouterClasse.clicked.connect(Dialog.pbAjouterClasse_clicked)
        self.pbModifierClasse.clicked.connect(Dialog.pbModifierClasse_clicked)
        self.twMatieres.itemClicked['QTableWidgetItem*'].connect(Dialog.on_administration_selection_matiere)
        self.pbAjouterMatiere.clicked.connect(Dialog.pbAjouterMatiere_clicked)
        self.pbSupprimerMatiere.clicked.connect(Dialog.pbSupprimerMatiere_clicked)
        self.pbModifierMatiere.clicked.connect(Dialog.pbModifierMatiere_clicked)
        self.twProfesseurs.itemClicked['QTableWidgetItem*'].connect(Dialog.on_administration_selection_professeur)
        self.pbAjouterProfesseur.clicked.connect(Dialog.pbAjouterProfesseur_clicked)
        self.pbSupprimerProfesseur.clicked.connect(Dialog.pbSupprimerProfesseur_clicked)
        self.pbModifierProfesseur.clicked.connect(Dialog.pbModifierProfesseur_clicked)
        self.twAdministrationEleves.itemClicked['QTableWidgetItem*'].connect(Dialog.on_administration_selection_eleve)
        self.pbAjouterEleve.clicked.connect(Dialog.pbAjouterEleve_clicked)
        self.pbSupprimerEleve.clicked.connect(Dialog.pbSupprimerEleve_clicked)
        self.pbModifierEleve.clicked.connect(Dialog.pbModifierEleve_clicked)
        Dialog.finished['int'].connect(Dialog.on_close)
        self.cbIdentificationProfesseur.currentTextChanged['QString'].connect(Dialog.on_professeur_identification)
        self.pbAjouterDevoir.clicked.connect(Dialog.pbAjouterDevoir_clicked)
        self.pbSupprimerDevoir.clicked.connect(Dialog.pbSupprimerDevoir)
        self.cbSelectionClasseProfesseur.currentTextChanged['QString'].connect(Dialog.on_identification_classe_changed)
        self.cbSelectionMatiereProfesseur.currentTextChanged['QString'].connect(Dialog.on_identification_matiere_changed)
        self.pbEnregistrerNotes.clicked.connect(Dialog.pbEnregistrerNotes_clicked)
        self.cbDevoirSelectionDevoirEnregistrerNotes.currentTextChanged['QString'].connect(Dialog.on_selection_devoir_changed)
        self.leNouveauDevoir.textChanged['QString'].connect(Dialog.on_ajouter_devoir_changed)
        self.cbSelectionDevoirSupprimer.currentTextChanged['QString'].connect(Dialog.on_supprimer_devoir_changed)
        self.cbAssociationProfesseur.currentTextChanged['QString'].connect(Dialog.on_association_identification_changed)
        self.cbSelectionClasseEleve.currentTextChanged['QString'].connect(Dialog.on_eleve_classe)
        self.cbIdentificationEleve.currentTextChanged['QString'].connect(Dialog.on_eleve_identification)
        self.cbSelectionMatiereEleve.currentTextChanged['QString'].connect(Dialog.on_eleve_matiere)
        self.tabApplication.currentChanged['int'].connect(Dialog.on_change_tab)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "GNL - Gestion de Notes Lycée"))
        self.groupBox.setTitle(_translate("Dialog", "Classes"))
        self.label.setText(_translate("Dialog", "Année scolaire :"))
        self.label_5.setText(_translate("Dialog", "Niveau :"))
        self.label_2.setText(_translate("Dialog", "Classe"))
        self.label_3.setText(_translate("Dialog", "Niveau"))
        self.label_4.setText(_translate("Dialog", "Professeur principal"))
        self.pbAjouterClasse.setText(_translate("Dialog", "Ajouter"))
        self.pbSupprimerClasse.setText(_translate("Dialog", "Supprimer"))
        self.pbModifierClasse.setText(_translate("Dialog", "Modifier"))
        self.groupBox_2.setTitle(_translate("Dialog", "Matières"))
        self.label_7.setText(_translate("Dialog", "Libellé de la matière : "))
        self.label_8.setText(_translate("Dialog", "Description : "))
        self.pbAjouterMatiere.setText(_translate("Dialog", "Ajouter"))
        self.pbSupprimerMatiere.setText(_translate("Dialog", "Supprimer"))
        self.pbModifierMatiere.setText(_translate("Dialog", "Modifier"))
        self.groupBox_3.setTitle(_translate("Dialog", "Professeurs"))
        self.label_9.setText(_translate("Dialog", "NUMEN :"))
        self.label_11.setText(_translate("Dialog", "Nom : "))
        self.label_10.setText(_translate("Dialog", "Prénom : "))
        self.pbAjouterProfesseur.setText(_translate("Dialog", "Ajouter"))
        self.pbSupprimerProfesseur.setText(_translate("Dialog", "Supprimer"))
        self.pbModifierProfesseur.setText(_translate("Dialog", "Modifier"))
        self.groupBox_4.setTitle(_translate("Dialog", "Elèves"))
        self.label_12.setText(_translate("Dialog", "INE : "))
        self.label_6.setText(_translate("Dialog", "Classe : "))
        self.label_13.setText(_translate("Dialog", "Nom : "))
        self.label_14.setText(_translate("Dialog", "Prénom : "))
        self.pbAjouterEleve.setText(_translate("Dialog", "Ajouter"))
        self.pbSupprimerEleve.setText(_translate("Dialog", "Supprimer"))
        self.pbModifierEleve.setText(_translate("Dialog", "Modifier"))
        self.tabApplication.setTabText(self.tabApplication.indexOf(self.tabAdministration), _translate("Dialog", "Administration"))
        self.gbIdentificationProfesseur.setTitle(_translate("Dialog", "Identification :"))
        self.label_15.setText(_translate("Dialog", "Professeur :"))
        self.label_20.setText(_translate("Dialog", "Classe :"))
        self.label_16.setText(_translate("Dialog", "Matières  :"))
        self.gbIdentificationProfesseur_3.setTitle(_translate("Dialog", "Ajouter/Suprimer un devoir"))
        self.label_24.setText(_translate("Dialog", "Devoir à ajouter :"))
        self.pbAjouterDevoir.setText(_translate("Dialog", "Ajouter"))
        self.label_26.setText(_translate("Dialog", "Devoir à supprimer :"))
        self.pbSupprimerDevoir.setText(_translate("Dialog", "Supprimer"))
        self.gbIdentificationProfesseur_2.setTitle(_translate("Dialog", "Notes"))
        self.label_18.setText(_translate("Dialog", "Sélectionner un devoir :"))
        self.pbEnregistrerNotes.setText(_translate("Dialog", "Enregistrer"))
        self.twProfesseurAfficherNotes.setSortingEnabled(False)
        self.tabApplication.setTabText(self.tabApplication.indexOf(self.tabProfesseur), _translate("Dialog", "Professeur"))
        self.gbIdentificationProfesseur_4.setTitle(_translate("Dialog", "Identification :"))
        self.label_17.setText(_translate("Dialog", "Professeur :"))
        self.label_19.setText(_translate("Dialog", "NUMEN : "))
        self.gbEnseigne.setTitle(_translate("Dialog", "Enseigne"))
        self.tabApplication.setTabText(self.tabApplication.indexOf(self.tabAssociation), _translate("Dialog", "Association"))
        self.gbIdentificationEleve.setTitle(_translate("Dialog", "Identification :"))
        self.label_22.setText(_translate("Dialog", "Classe :"))
        self.label_21.setText(_translate("Dialog", "Elève : "))
        self.label_23.setText(_translate("Dialog", "Matières  :"))
        self.gbNotesEleve.setTitle(_translate("Dialog", "Notes"))
        self.twEleveAfficherNotes.setSortingEnabled(False)
        self.tabApplication.setTabText(self.tabApplication.indexOf(self.tabEleve), _translate("Dialog", "Eleve"))
